### ISSUE TITLE
Not Working with V2 of RedBear Shield

### ISSUE THREAD

**Issue by robotastic** [guyzmo/avr_nrf_ancs_library#2]
I haven't been able to get the library up and running with V2.0 of the RedBear Shield. It looks like the library has been updated from the one you include. Would simply switch to the new library fix things? Any thoughts on what else could be wrong?

**Comment by guyzmo** [comment]
I sadly don't have access to my red bear lab shield anymore, though it was a v2 for sure, and the whole was working. Though you have to setup the pins accordingly to the defines in the `.ino` file. Check:

https://github.com/guyzmo/avr_nrf_ancs_library/blob/master/avr_nrf_ancs_library.ino#L36

and configure the jumpers accordingly.

The library is not the latest, and I did not look for the differences nordic has implemented since then, if I could I'd even consider use their new (relatively to my code) github repository as git submodule instead of keeping a copy of it in my code.

Though, about your _up and running_ problem, can you be a bit more specific about the trouble you're running into? I'd be happy to help you get through that so you can fix what's wrong and eventually submit a pull request to fix and update my code! :-)

N.B.: you should try first the code by using `make DEFINES="-DNO_ANCS"` to compile, so you can test the part that works only with getting notifications not getting all the details. I know, the `NO_ANCS` define is misleading, what it means it does not load the more complex ANCS LIB from within my code that handles getting attributes. Which part has a bug I spotted, cf ticket #1.

**Comment by robotastic** [comment]
Thanks for replying so quickly! Good point - here are some more details on my setup and what I got working:
OSX 10.10 ( I will also try on Mavericks)
Arduino IDE 1.05
Arduino Leonardo
RedBear BLE Shield v2.0
iPhone 5s

I am building it in the IDE instead of the command line. I have a Linux VM, so I could try doing it in there instead if that is better.

For some reason, I am having a real issue with Serial << and F(), so I removed both and just did Serial.print. I was getting this error: __c causes a section type conflict

Right now I am using the version BLE Lib that is part of your bundle. I will try switching to the newer library, but it looks like it breaks some function calls.

For the pins - I set my jumpers for REQN and REDY are the same. I am not sure how to wire the Interrupt to Pin, or what I am supposed to do with pin 1. I set it to UNUSED. The same with the pin SS for HAL_IO_RADIO_CSN;

I don't have the jumper for RESET_RF, on my board it can be 4 or 7.

I did clear the EEPROM out to get rid of any old bonding info: EEPROM.write(0, 0xFF)

I am using the LightBlue app on the iPhone to find the BLE Shield and Pair/Bond. I got the dialog for the pin and was able to type it and then query values. However, the arduino is not discovering any of the ANCS services and when I try sending myself a message I don't get any notifications.

Here is the debug output from the serial monitor. Any other things I can try? I did define NO_ANCS. More than happy to submit the code back once I figure out what is up... and I will even write a getting started guide!

```
nRF8001 setup: done
ANCS setup: [free SRAM] 194 bytes
done
New evt received: Evt Device Started: Setup
New evt received: Evt Device Started: Standby
No Bond present in EEPROM.
Advertising started : Waiting to be connected and bonded
New evt received: Evt Command Response: Bond: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Pipe Status
New evt received: Evt Display Passkey: [ 0 7 4 8 4 3 ]
New evt received: Evt Bond Status
New evt received: Evt Pipe Status
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Dynamic Data read and stored successfully
Disconnected: 2
Using existing bond stored in EEPROM.
Advertising started. Connecting.
[free SRAM] 197 bytes
New evt received: Evt Command Response: Connect: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Pipe Status
 Service Discovery is over.
New evt received: Evt Command Response: Change Timing: Success!
New evt received: Evt link connection interval changed
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Disconnected: 13
Using existing bond stored in EEPROM.
Advertising started. Connecting.
[free SRAM] 197 bytes
New evt received: Evt Command Response: Connect: Success!
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Using existing bond stored in EEPROM.
Advertising started. Connecting.
[free SRAM] 197 bytes
New evt received: Evt Command Response: Connect: Success!
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Using existing bond stored in EEPROM.
Advertising started. Connecting.
[free SRAM] 197 bytes
New evt received: Evt Command Response: Connect: Success!
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Using existing bond stored in EEPROM.
Advertising started. Connecting.
```

It just repeats the last couple of message while the iphone is in standby.

**Comment by robotastic** [comment]
Looks like I didn't have enough of the debug levels turned on. Here is more output. The odd thing is that when I try to use Debug level 3, the Arduino locks up and outputs tons of stuff to the console. I got around it by change the Service Discovery to Debug2.print. It still looks like the debug message for PIPE_ANCS_CONTROL_POINT_TX_ACK and PIPE_ANCS_DATA_SOURCE_RX get called a lot when I turn them on, which is weird. Anyhow, here is a better output:

```
nRF8001 setup: 1Pairing/Bonding info cleared from EEPROM.
Remove the wire on Pin 6 and reset the board for normal operation.
done
New evt received: Evt Device Started: Standby
No Bond present in EEPROM.
Advertising started : Waiting to be connected and bonded
New evt received: Evt Command Response: Bond: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Display Passkey: [ 2 7 3 9 7 3 ]
New evt received: Evt Pipe Status
New evt received: Evt Bond Status
New evt received: Evt Pipe Status
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 7, 
Here are the available closed pipes: 5, 6, 
 Service Discovery is over.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Failure opening.
New evt received: Evt Command Response: Change Timing: Success!
New evt received: Evt link connection interval changed
New evt received: Evt Command Response: Disconnect: Success!
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Dynamic Data read and stored successfully
Disconnected: 2
Using existing bond stored in EEPROM.
Advertising started. Connec
```

**Comment by robotastic** [comment]
OK - so the problem with the Debug Message might actually have to do with not enough flash memory for the strings or something like that. I remove some of the other debug messages and I was able to get them Service Discovery ones to work.

More importantly, I reread you blog post and I saw that bit about turning bluetooth off and then on. I did, that and it worked! I will have to play with this more tomorrow, but I atleast got some notifications and got new ones when I sent a message:

```
0
done
New evt received: Evt Device Started: Standby
No Bond present in EEPROM.
Advertising started : Waiting to be connected and bonded
New evt received: Evt Command Response: Bond: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Bond Status
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Advertising started. Bonding.
New evt received: Evt Command Response: Bond: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Display Passkey: [ 8 2 9 5 0 4 ]
New evt received: Evt Pipe Status
New evt received: Evt Bond Status
New evt received: Evt Pipe Status
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 7, 
Here are the available closed pipes: 5, 6, 
 Service Discovery is over.
ANCS Data Source available.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Failure opening.
New evt received: Evt Command Response: Change Timing: Success!
New evt received: Evt link connection interval changed
New evt received: Evt Command Response: Disconnect: Success!
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Dynamic Data read and stored successfully
Disconnected: 2
Using existing bond stored in EEPROM.
Advertising started. Connecting.
[free SRAM] 109 bytes
New evt received: Evt Command Response: Connect: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 7, 
Here are the available closed pipes: 5, 6, 
 Service Discovery is over.
ANCS Data Source available.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Failure opening.
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Command Response: Change Timing: Success!
New evt received: Evt link connection interval changed
New evt received: Evt Disconnected. Link Lost or Advertising timed out
Disconnected: 13
Using existing bond stored in EEPROM.
Advertising started. Connecting.
[free SRAM] 109 bytes
New evt received: Evt Command Response: Connect: Success!
New evt received: Evt Connected
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 7, 
Here are the available closed pipes: 5, 6, 
 Service Discovery is over.
ANCS Data Source available.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Failure opening.
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 
Here are the available closed pipes: 
 Service Discovery is still going on.
New evt received: Evt Command Response: Device Version: Success!
New evt received: Evt Command Response: Change Timing: Success!
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 7, 
Here are the available closed pipes: 5, 6, 
 Service Discovery is over.
ANCS Data Source available.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Failure opening.
New evt received: Evt Command Response: Open Remote Pipe: Success!
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 6, 7, 
Here are the available closed pipes: 5, 
 Service Discovery is over.
ANCS Data Source not available.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Success opening.
New evt received: Evt Command Response: Open Remote Pipe: Success!
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 5, 6, 7, 
Here are the available closed pipes: 
 Service Discovery is over.
ANCS Data Source not available.
  -> ANCS Notification Source not available.
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 0 ; Event type: ADDED ; Event Category: missed call
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 16777216 ; Event type: ADDED ; Event Category: missed call
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 33554432 ; Event type: ADDED ; Event Category: missed call
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 50331648 ; Event type: ADDED ; Event Category: missed call
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 67108864 ; Event type: ADDED ; Event Category: missed call
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 83886080 ; Event type: ADDED ; Event Category: missed call
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 100663296 ; Event type: ADDED ; Event Category: Ignored
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 117440512 ; Event type: ADDED ; Event Category: social msg
New evt received: Evt Pipe Status
phone detected.
Here are the available open pipes: 1, 2, 3, 4, 5, 6, 7, 
Here are the available closed pipes: 
 Service Discovery is over.
ANCS Data Source not available.
  -> ANCS Notification Source not available.
New evt received: Evt link connection interval changed
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 134217728 ; Event type: ADDED ; Event Category: social msg
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 117440512 ; Event type: REMOVED
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 150994944 ; Event type: ADDED ; Event Category: social msg
New evt received: Evt Data Received
NOTIFICATION SOURCE
Notif Id: 134217728 ; Event type: REMOVED
```

**Comment by guyzmo** [comment]
Well, you've done quite a bit, during the night. 

> OK - so the problem with the Debug Message might actually have to do with not enough flash memory for the strings or something like that. I remove some of the other debug messages and I was able to get them Service Discovery ones to work.

First of all, the problem you're having with the memory exhaustion comes from the fact that you've actually removed the `F()` which keeps the strings in the flash memory instead of loading them into the RAM in runtime.

But it's also what can create the `__c causes a section type conflict`… You can search for that, you'll see it's a fairly common problem, and there are lots of ways to deal with that.

> More importantly, I reread you blog post and I saw that bit about turning bluetooth off and then on. I did, that and it worked!

About the reconnection, at some point you're getting `Disconnected: 2`, which is done [here](https://github.com/guyzmo/avr_nrf_ancs_library/blob/master/avr_nrf_ancs_library.ino#L253) to actually force the required disconnect/reconnect. Though, that's one thing that should have got solved by nordic for their library, over the last 6 months I finished working on that library.

**Comment by robotastic** [comment]
Ahh - ok I am going to try and rebaseline the code against the updated
Nordic libraries. Thanks for the explanation on the memory and F().

On wiring up the BLE Shield, should I be doing something with Pin #1? I
wasn't sure based upon this line:
https://github.com/guyzmo/avr_nrf_ancs_library/blob/master/avr_nrf_ancs_library.ino#L40

I also wasn't sure if I needed to do something special to enable CSN/SS
based upon this line:
https://github.com/guyzmo/avr_nrf_ancs_library/blob/master/avr_nrf_ancs_library.ino#L36

Thanks again for your help. I will do fork and pull with whatever I come up
with.

**Comment by guyzmo** [comment]
On Mon, Aug 11, 2014 at 11:09:46AM -0700, Luke Berndt wrote:

> Ahh - ok I am going to try and rebaseline the code against the updated
> Nordic libraries. Thanks for the explanation on the memory and F().

That's definitely nice!

Go for it! And if you can make it more memory efficient, don't hesitate.
Read the wiki to see how it works, but you should be able to experiment
pretty easily on the memory model, as this is encapsulated away from the
protocol implementation itself (All the notification list stuff,
basically). 

I tried to minimize as much as possible the risk of heap/stack smashing 
and order correctly the malloc/free operations, but it still can happen.

Finally, I'm a bit puzzled that the `operator<<()` stuff on the Serial
port does not work fine for you. It's definitely a great hack for all
the libraries that are not bound to the MCU, to be able to work some
unit testing out (basically, `#define Serial std::cout` and there you go!).

> On wiring up the BLE Shield, should I be doing something with Pin #1? I
> wasn't sure based upon this line:
> https://github.com/guyzmo/avr_nrf_ancs_library/blob/master/avr_nrf_ancs_library.ino#L40

Nope, I forgot to document that, but this is not a pin number, it's an
interrupt number. As the BLE library is _not_ an arduino library,
there's no "magic" going on to match pins with interrupt vectors. As on
the project I worked on, we were using an atmega32u4 with a pin on
another interrupt vector, I had to extract that one out to make it
settable.

Though it would definitely not hurt documenting that ;-)

> I also wasn't sure if I needed to do something special to enable CSN/SS
> based upon this line:
> https://github.com/guyzmo/avr_nrf_ancs_library/blob/master/avr_nrf_ancs_library.ino#L36

I'm not sure of that one, but if I'm not wrong, the `SS` pin is part of
the `ICSP` header, containing the `ISP` pins. So ignoring it should be
fine.

**Comment by robotastic** [comment]
I ported your code to the latest Proximity Example and the latest BLE library. The notifications work great. When I turn off #define NO_ANCS I am having trouble reading in the attributes to get the information on the notification. I am wondering if it has to do with free RAM. I will work on getting the RAM usage lower and see if that helps.

My code is here: https://github.com/robotastic/avr_nrf_ancs_library

I will do a pull request once I get the ANCS Lib stuff working. 

Thanks again for building this awesomeness!!

**Comment by guyzmo** [comment]
I have made a bunch of comments on your .ino change, I did not read it thoroughly, though. Don't hesitate to come back with questions, as there a bunch of things that I did modify and may not have documented correctly.

For example, the fact that I changed the original proximity code, so it addresses any bonding situation, like ios has bonding info, but not device and vice versa. The possibility to reset bonding data from the device using a service pipe. And never going into an infinite empty loop…

The fact that you've changed all litteral strings to be in memory, will eat your memory up too much. You should rollback that to use the `F()` macro the soonest. If you're running into `__c` problem, then just rollback the last `F()` you've added. Usually, I've noticed that it happens when you have two strings with an identical substring… But it's certainly not that simple.

About the ANCS lib itself, don't forget there's a double free bug I did not fix, because I couldn't test the fix. Look at the other issue and the comments in the source code, and please test the fix for me! :-) Don't forget there's a wiki page explaining the working of the ANCS lib, [here](https://github.com/guyzmo/avr_nrf_ancs_library/wiki/Sequence), which will help you a lot if you want to change things in the memory model part.

**Comment by robotastic** [comment]
Cool!
All good points - am going to keep it "services.h" for now because I am sharing the BLE library on some other Arduino sketches. 

I switched the bonding code back to the way you had. That seems much better.

I am going to work on the ANCS Lib tonight. I am also switching back to F(). I didn't think to check the wiki and that is a great starting point.

**Comment by guyzmo** [comment]
well, you can keep it at the root, and use `<services.h>` ;-)
AFAICT, arduino is doing a `-I.` per default.

**Comment by guyzmo** [comment]
>  All good points - am going to keep it "services.h" for now because I am sharing the BLE library on some other Arduino sketches. 

you should be able to keep it as `#include <services.h>`, as _afaict_ the arduino IDE does `-I.` at compilation time. My Makefile does it as well. So when you'll move the file around, you won't have to change the code.

> I switched the bonding code back to the way you had. That seems much better.

great!

> I am going to work on the ANCS Lib tonight.

nice, if you test and fix #1 I'll give you a hug if we meet :-)

> I am also switching back to F()

:+1:

**Comment by robotastic** [comment]
Sorry - I have one last question. Is there anyway to do the bonding with the iPhone without requiring a PassKey? I checked the nrf8001_ancs.xml file in nRFGoStudio and it looks like DisplayOnly is set in security.

Would advertising the ANCS UUID from the BLE Shield change how iOS pairs with it? It might make it possible to simply pair with it through the iOS->Settings-> Bluetooth menu and simply do a click to pair instead of entering a passkey.

I am asking because I don't want to have to add a display to my arduino to display the passkey and looking around it seems like other devices are able to pair without entering the passkey.

**Comment by robotastic** [comment]
It looks like there is an Unauthenticated(Just Works) setting under Security. I will try using that instead and see if it works.

**Comment by robotastic** [comment]
So you can get it to pair & bond fine without a passkey. You just need to goto the security tab, "enable security" and then set Required Level of Security to Unauthenticated "JustWorks". Then the most important step is to set I/O Capabilities to None.

I am having issues getting the ANCS Lib up and running, when I enable it, it can parse the Notifications fine, but it looks like it is failing to send out request to get more data on the notifications, It should also be printing out ""[ANCS NS]    ancs_get_notification_data(): end" but I don't see it anywhere. I am not sure if the function is getting tossed off the stack for some reason. I am sure why the function doesn't run in full... I will keep poking.

```
Evt Connected
Evt Pipe Status
Evt Command Response: : Success!
Device Version
Evt Pipe Status
Evt Bond Status
Evt Pipe Status
phone Detected.
 Service Discovery is over.
  -> ANCS Control Point not available.
  -> ANCS Data Source available.
  -> ANCS Data Source Pipe: Success opening.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Success opening.
Evt Command Response: : Success!
Open Remote Pipe
Evt Command Response: : failed with error 'command rejected'
Open Remote Pipe
Evt Pipe Status
phone Detected.
 Service Discovery is over.
  -> ANCS Control Point not available.
  -> ANCS Data Source not available.
  -> ANCS Notification Source available.
  -> ANCS Notification Source Pipe: Success opening.
Evt Command Response: : Success!
Open Remote Pipe
Evt Pipe Status
phone Detected.
 Service Discovery is over.
  -> ANCS Control Point not available.
  -> ANCS Data Source not available.
  -> ANCS Notification Source not available.
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #0: Category: 
Missed call
[free SRAM] 1281 bytes
[ANCS NS] ancs_get_notification_data(
0)
[free SRAM] 1161 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #1: Category: 
Missed call
[free SRAM] 1169 bytes
[ANCS NS] ancs_get_notification_data(
1)
[free SRAM] 1059 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #2: Category: 
Missed call
[free SRAM] 1067 bytes
[ANCS NS] ancs_get_notification_data(
2)
[free SRAM] 971 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #3: Category: 
Missed call
[free SRAM] 979 bytes
[ANCS NS] ancs_get_notification_data(
3)
[free SRAM] 869 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #4: Category: 
Missed call
[free SRAM] 877 bytes
[ANCS NS] ancs_get_notification_data(
4)
[free SRAM] 767 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #5: Category: 
Missed call
[free SRAM] 775 bytes
[ANCS NS] ancs_get_notification_data(
5)
[free SRAM] 665 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #6: Category: 
Missed call
[free SRAM] 673 bytes
[ANCS NS] ancs_get_notification_data(
6)
[free SRAM] 563 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #7: Category: 
Missed call
[free SRAM] 571 bytes
[ANCS NS] ancs_get_notification_data(
7)
[free SRAM] 461 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #8: Category: 
Missed call
[free SRAM] 469 bytes
[ANCS NS] ancs_get_notification_data(
8)
[free SRAM] 359 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #9: Category: 
Missed call
[free SRAM] 367 bytes
[ANCS NS] ancs_get_notification_data(
9)
[free SRAM] 257 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #10: Category: 
Missed call
[free SRAM] 265 bytes
[ANCS NS] ancs_get_notification_data(
10)
[free SRAM] 155 bytes
Evt Data Received
[ANCS NS] ancs_notification_source_parser()
N #11: Category: 
[free SRAM] 163 bytes
[ANCS NS] ancs_get_notification_data(
11)
```

**Comment by guyzmo** [comment]
> So you can get it to pair & bond fine without a passkey. You just need to goto the security tab, "enable security" and then set Required Level of Security to Unauthenticated "JustWorks". Then the most important step is to set I/O Capabilities to None.

weird, I remember that was not working.

> I am having issues getting the ANCS Lib up and running, when I enable it, it can parse the Notifications fine, but it looks like it is failing to send out request to get more data on the notifications, It should also be printing out `[ANCS NS] ancs_get_notification_data(): end` but I don't see it anywhere. I am not sure if the function is getting tossed off the stack for some reason. I am sure why the function doesn't run in full... I will keep poking.

that's where it hurts, though I've built it so theoretically, each notification can be processed as they come, so we never actually store than one notification at a time in the memory. Though, it's the tweaking that you're doing in the other ticket ;-)

**Comment by robotastic** [comment]
It actually have it up and running pretty well now. I still have to clean it up and test it a bit more before I merge more fork back in.

I am working on trying to bond directly with the BLE Shield from the iOS Bluetooth settings menu, but I can't get it to work. I am able to see it in the list of devices, but when I click on it, it just connects instead of pairing. However, when I use the lightblue app to interrogate the BLE Shield the request to pair dialog comes up. Clearly the lightblue app is doing a deeper discovery. Any tips on things to try? I did a longer writeup here: https://devzone.nordicsemi.com/question/15140/ancs-bonding-without-an-app/

**Comment by guyzmo** [comment]
yup.

From my experience with BTLE, and reading documentation on the subject, that's actually not a bug but a feature in how iOS works. Look at the CoreBluetooth video from WWDC 2013, where they introduced BTLE support in iOS, they've made it so the device is actually linked to an app.

Their process is basically to have the app setup the connection to a kind of device, the OS then handling the connection and bonding like for any bluetooth device, and once bonded the OS stores that the given BTLE device is linked with a given app using their background callback feature.

It's only in that scenario that the ANCS is brought up to the external device, which from Apple's point of view makes sense, as to enforce isolation, any action on service's characteristics you might want to do, upon receival of notifications, has to be sent back to and processed by the linked application.

**Comment by robotastic** [comment]
Actually it turns out there are 2 different BTLE profiles that iOS will display, HID and ANCS. When you do a Service Solicitation with the ANCS it shows up on the iOS Bluetooth Settings menu. In order to get it to work with iOS and do a pairing, I needed to bond security request call:

```
if (lib_aci_is_discovery_finished(&aci_state) && (ACI_BOND_STATUS_SUCCESS != aci_state.bonded)) {
                debug_println(F("Upgrading security!"));
                lib_aci_bond_request();
            }
```

Anyhow - I think I have everything working. I can pull attributes from notifications and pair without a passkey from the iOS bluetooth menu. Everything is up on my fork: https://github.com/robotastic/avr_nrf_ancs_library

I still need to do some more testing and update the docs, but so far it is pretty cool!
