### ISSUE TITLE
Can not use with a Arduino uno

### ISSUE THREAD

**Issue by goofmint** [guyzmo/avr_nrf_ancs_library#3]
I'm using a Arduino uno. And I'm trying your library.

```
$ sudo dfu-programmer atmega16u2 erase
$ make flush all
$ sudo dfu-programmer atmega16u2 flash applet/avr_nrf_ancs_library.hex --suppress-bootloader-mem
Validating...
15482 bytes used (125.99%)
```

almost done. But I can not view any usb ports.

```
$ ls /dev/c*
/dev/console            /dev/cu.Bluetooth-Modem
/dev/cu.Bluetooth-Incoming-Port
```

Normal, I'm using "/dev/cu.usbmodemfd121".

So I cannot send to Arduino any program. Maybe I think Arduino uno use serial to usb, but Leonardo is not.

My env.
- Mac OSX 10.9.4
- Arduino uno
- dfu-programmer 0.6.2

Help me.

Thanks.

**Comment by guyzmo** [comment]
Hi,

here's your problem `15482 bytes used (125.99%)`, the firmware is bigger than the available memory, as it says. Which is expectable, as you're flashing in the `16u2`, not the `328` microcontroller.

So, what I'm actually wondering is why you're actually flashing that within the `16u2` using `dfu-programmer`, whereas the whole point of the 16u2 is to make the USB-UART bridge. On the Uno, you want to use the `Atmega328`. And to flash it, you need to use `avrdude`.

I've included a `Makefile` in the project, and the use of the Makefile is explained in the `README`. To use the Makefile, you'll need the arduino application installed as `/Applications/Arduino.app`.

**Comment by goofmint** [comment]
Hi, @guyzmo .
Thank you for reply!

125.99%...Oh, I didn't see that, thank. I'll try again!

Regards.

**Comment by guyzmo** [comment]
well that, but working on the wrong target is even worse… reflashing the atmega16u2 is only useful to change how you computer sees the arduino (to build an HID device for example instead of a serial device)…
